# -*- coding: utf-8 -*-
"""mscproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPBFuUTsgCZ8NGWkDkPWTqF5VXg1wQ3_
"""

!pip install -q bitsandbytes
!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install -q transformers accelerate
!pip install -q "trl>=0.12.0"
!pip install -q datasets peft sentence-transformers pillow scipy openai
!pip install -q groq

import trl
print("trl version:", trl.__version__)
print("PPO names:", [n for n in dir(trl) if "ppo" in n.lower() or "PPO" in n])

import torch
import numpy as np
import pandas as pd
import random, json, time
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from PIL import Image
from datasets import load_dataset
from transformers import BitsAndBytesConfig, LlavaForConditionalGeneration, AutoProcessor
from peft import LoraConfig, get_peft_model
from sentence_transformers import SentenceTransformer, util
from scipy import stats as scipy_stats
from scipy.stats import t as t_dist
import warnings

warnings.filterwarnings("ignore")

# trl is NOT imported — training uses a self-contained REINFORCE loop in Cell 13
print("All imports OK.")

CFG = {
    # Training
    "PPO_STEPS":            400,      # upgrade 1: was 50, now 300-500
    "TRAIN_ITEMS":          400,      # training questions from ScienceQA
    "LEARNING_RATE":        1e-5,
    "TEMPERATURE":          0.9,
    "MAX_NEW_TOKENS":       50,

    # Evaluation
    "TEST_ITEMS":           500,      # upgrade 2: was 100, now 500+
    "EVAL_TEMPERATURE":     0.7,

    # Seeds
    "SEEDS":                [42, 123, 7],

    # Reward / FGM
    "HALLUCINATION_THRESHOLD": 0.6,
    "W_TASK":               1.0,
    "W_FACT":               0.5,
    "PENALTY":             -0.5,
    "LORA_RANK":            16,
    "FGM_THRESHOLD":   0.6,

    # LLM-as-Judge
    "JUDGE_SAMPLE_SIZE":    50,       # upgrade 4: GPT-4 judge on 50 samples
    "OPENAI_MODEL":         "gpt-4o-mini",  # cheaper than gpt-4, still powerful

    # Confidence intervals
    "CI_LEVEL":             0.95,     # upgrade 5: 95% CI

     # RAG baseline
    "RAG_TOP_K":            3,        # number of passages retrieved per query
    "RAG_CORPUS_MAX":       400,      # max corpus passages (same as TRAIN_ITEMS)
}


print("Config loaded:")
for k, v in CFG.items():
    print(f"  {k:<30} {v}")

def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(CFG["SEEDS"][0])

from huggingface_hub import login
login(token="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")

# Set your OpenAI key for LLM-as-Judge (upgrade 4)
import os

os.environ["GROQ_API_KEY"] = "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"   # ← paste your Groq key here
print("Groq key set.")

print("Loading ScienceQA...")
scienceqa = load_dataset("derek-thomas/ScienceQA")

def build_question_list(split: str, max_items: int, seed: int = 42) -> list:
    """
    Returns a reproducible shuffled list of ScienceQA items that have images.
    Using the same seed guarantees identical ordering across agents and seeds.
    """
    raw = [item for item in scienceqa[split] if item["image"] is not None]
    random.seed(seed)
    random.shuffle(raw)
    out = []
    for item in raw[:max_items]:
        choices = item["choices"]
        out.append({
            "prompt":       item["question"],
            "image":        item["image"],            # PIL Image — no URL needed
            "ground_truth": choices[item["answer"]],  # expert-annotated label
            "choices":      choices,
        })
    return out

# Fixed shared test set — never reshuffled
SHARED_TEST_SET  = build_question_list("test",  max_items=CFG["TEST_ITEMS"],  seed=42)
TRAIN_QUESTIONS  = build_question_list("train", max_items=CFG["TRAIN_ITEMS"], seed=42)

print(f"Shared test set : {len(SHARED_TEST_SET)} items  (seed=42, frozen)")
print(f"Training set    : {len(TRAIN_QUESTIONS)} items  (seed=42)")
print(f"Example Q       : {SHARED_TEST_SET[0]['prompt']}")
print(f"Ground truth    : {SHARED_TEST_SET[0]['ground_truth']}")

import torch, gc

# Kill everything in GPU memory
gc.collect()
torch.cuda.empty_cache()
torch.cuda.synchronize()

# If a previous model is still loaded, delete it
for var in ['model', 'vanilla_model', 'std_ppo_model', 'rag_model']:
    if var in dir():
        exec(f'del {var}')

gc.collect()
torch.cuda.empty_cache()

free, total = torch.cuda.mem_get_info()
print(f"VRAM free:  {free/1024**3:.2f} GB")
print(f"VRAM total: {total/1024**3:.2f} GB")
print(f"VRAM used:  {(total-free)/1024**3:.2f} GB")

# CELL 6 — LOAD PROCESSOR ONLY
# The base model is NOT loaded here.
# Loading it now wastes 6 GB VRAM needed for training.
# make_lora_model() / make_vanilla_model() (defined in Cell 7)
# load a fresh copy on demand and are deleted after each experiment.
from transformers import AutoProcessor
processor = AutoProcessor.from_pretrained("llava-hf/llava-1.5-7b-hf")
print("✓ Processor loaded. No model in VRAM yet.")

import torch
free, total = torch.cuda.mem_get_info()
print(f"  VRAM free: {free/1024**3:.2f} GB / {total/1024**3:.2f} GB")

# CELL 7 — MODEL FACTORY (defines functions only, loads nothing)
from transformers import LlavaForConditionalGeneration, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model
import torch, gc

def make_lora_model():
    """Load fresh 4-bit LLaVA + LoRA. Call once per experiment, then del."""
    gc.collect(); torch.cuda.empty_cache()
    free, total = torch.cuda.mem_get_info()
    print(f"  VRAM before load: {free/1024**3:.2f} GB free")
    m = LlavaForConditionalGeneration.from_pretrained(
        "llava-hf/llava-1.5-7b-hf",
        quantization_config=BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.float16,
        ),
        device_map="auto",
        low_cpu_mem_usage=True,
    )
    lora_cfg = LoraConfig(
        r=16, lora_alpha=32, lora_dropout=0.05,
        bias="none", task_type="CAUSAL_LM",
        target_modules=["q_proj", "v_proj"],
    )
    m = get_peft_model(m, lora_cfg)
    m.print_trainable_parameters()
    free2, _ = torch.cuda.mem_get_info()
    print(f"  VRAM after load:  {free2/1024**3:.2f} GB free")
    return m

def make_vanilla_model():
    """Load fresh 4-bit LLaVA, no LoRA. Call once per experiment, then del."""
    gc.collect(); torch.cuda.empty_cache()
    m = LlavaForConditionalGeneration.from_pretrained(
        "llava-hf/llava-1.5-7b-hf",
        quantization_config=BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.float16,
        ),
        device_map="auto",
        low_cpu_mem_usage=True,
    )
    free, total = torch.cuda.mem_get_info()
    print(f"  Vanilla loaded. VRAM free: {free/1024**3:.2f} GB")
    return m

print("✓ make_lora_model / make_vanilla_model defined.")
print("  No model in VRAM. Run experiments in order from Cell 15.")
free, total = torch.cuda.mem_get_info()
print(f"  VRAM free: {free/1024**3:.2f} GB / {total/1024**3:.2f} GB")

class FactualGroundingModule:
    """
    Scores semantic alignment between generated response and ground truth
    using all-MiniLM-L6-v2 cosine similarity. Returns score in [0, 1].
    """
    def __init__(self):
        print("Loading FGM (all-MiniLM-L6-v2)...")
        self.model = SentenceTransformer("all-MiniLM-L6-v2")
        print("FGM ready.")

    def verify_step(self, generated: str, ground_truth: str) -> float:
        e1 = self.model.encode(generated,    convert_to_tensor=True)
        e2 = self.model.encode(ground_truth, convert_to_tensor=True)
        return float(util.pytorch_cos_sim(e1, e2).item())

fgm = FactualGroundingModule()

REWARD_CONFIGS = {
    "A: Task Only":    {"W_TASK":1.0, "W_FACT":0.0, "PENALTY": 0.0,  "THRESHOLD":0.6, "standard_ppo":False},
    "B: Fact Only":    {"W_TASK":0.0, "W_FACT":1.0, "PENALTY":-0.5,  "THRESHOLD":0.6, "standard_ppo":False},
    "C: No Penalty":   {"W_TASK":1.0, "W_FACT":0.5, "PENALTY": 0.0,  "THRESHOLD":0.6, "standard_ppo":False},
    "D: Full HRA":     {"W_TASK":1.0, "W_FACT":0.5, "PENALTY":-0.5,  "THRESHOLD":0.6, "standard_ppo":False},
    "E: Standard PPO": {"W_TASK":1.0, "W_FACT":0.0, "PENALTY": 0.0,  "THRESHOLD":0.6, "standard_ppo":True},
}

def calculate_reward(task_success: bool, factuality_score: float, config_name: str) -> float:
    """
    Computes the reward signal for a given configuration.
    Config E (Standard PPO) uses a single binary scalar — no factuality component.
    This is the standard approach in the literature against which HRA is compared.
    """
    cfg = REWARD_CONFIGS[config_name]

    if cfg["standard_ppo"]:
        # Baseline E: pure binary outcome reward — standard PPO in the literature
        return 1.0 if task_success else 0.0

    r_task = 1.0 if task_success else 0.0
    r_fact = (factuality_score * 0.2) if factuality_score >= cfg["THRESHOLD"] \
             else cfg["PENALTY"]
    return (cfg["W_TASK"] * r_task) + (cfg["W_FACT"] * r_fact)

print("Reward configs ready. Baselines: Vanilla, Standard PPO (E), and Full HRA (D).")

def cohens_d(group1: list, group2: list) -> float:
    """
    Cohen's d effect size between two groups.
    d = (mean1 - mean2) / pooled_std
    Interpretation: small=0.2, medium=0.5, large=0.8
    """
    n1, n2   = len(group1), len(group2)
    mean1    = np.mean(group1)
    mean2    = np.mean(group2)
    var1     = np.var(group1, ddof=1)
    var2     = np.var(group2, ddof=1)
    pooled_std = np.sqrt(((n1 - 1) * var1 + (n2 - 1) * var2) / (n1 + n2 - 2))
    if pooled_std == 0:
        return 0.0
    return float((mean1 - mean2) / pooled_std)

def interpret_cohens_d(d: float) -> str:
    d = abs(d)
    if d < 0.2:  return "negligible"
    if d < 0.5:  return "small"
    if d < 0.8:  return "medium"
    return "large"

def confidence_interval_mean(data: list, confidence: float = 0.95) -> tuple:
    """
    Returns (lower, upper) bounds of the confidence interval for the mean.
    Uses t-distribution (appropriate for small sample sizes like 3 seeds).
    """
    n    = len(data)
    mean = np.mean(data)
    se   = scipy_stats.sem(data)       # standard error of the mean
    h    = se * t_dist.ppf((1 + confidence) / 2.0, df=n - 1)
    return float(mean - h), float(mean + h)

def full_stats(values: list, label: str = "", ci: float = 0.95) -> dict:
    """
    Returns a complete statistics dict for a list of values:
    mean, std, CI lower/upper, min, max.
    """
    arr  = np.array(values)
    lo, hi = confidence_interval_mean(values, ci)
    return {
        "label": label,
        "n":     len(values),
        "mean":  round(float(arr.mean()), 4),
        "std":   round(float(arr.std()),  4),
        "ci_lo": round(lo, 4),
        "ci_hi": round(hi, 4),
        "min":   round(float(arr.min()), 4),
        "max":   round(float(arr.max()), 4),
    }

def compare_two_groups(group_a: list, group_b: list,
                       label_a: str = "A", label_b: str = "B",
                       metric: str = "", ci: float = 0.95) -> dict:
    """
    Full statistical comparison: t-test, p-value, effect size, CIs.
    """
    t_stat, p_val = scipy_stats.ttest_rel(group_a, group_b)
    d             = cohens_d(group_a, group_b)
    stats_a       = full_stats(group_a, label_a, ci)
    stats_b       = full_stats(group_b, label_b, ci)

    print(f"\n  {metric} — {label_a} vs {label_b}")
    print(f"    {label_a}: {stats_a['mean']:.4f} ± {stats_a['std']:.4f}  "
          f"95% CI [{stats_a['ci_lo']:.4f}, {stats_a['ci_hi']:.4f}]")
    print(f"    {label_b}: {stats_b['mean']:.4f} ± {stats_b['std']:.4f}  "
          f"95% CI [{stats_b['ci_lo']:.4f}, {stats_b['ci_hi']:.4f}]")
    print(f"    t={t_stat:.3f}  p={p_val:.4f}  d={d:.3f} ({interpret_cohens_d(d)})")
    sig = "SIGNIFICANT (p<0.05)" if p_val < 0.05 else "not significant"
    print(f"    {sig}")

    return {
        "metric":  metric,
        "t_stat":  round(t_stat, 4),
        "p_val":   round(p_val,  4),
        "cohens_d": round(d,     4),
        "effect_size": interpret_cohens_d(d),
        "significant": p_val < 0.05,
        **{f"{label_a}_{k}": v for k, v in stats_a.items()},
        **{f"{label_b}_{k}": v for k, v in stats_b.items()},
    }

print("Statistics helpers ready.")

from groq import Groq

class LLMJudge:
    """
    LLM-as-Judge using Groq API (free, fast).
    Default model: llama-3.1-8b-instant
    Scoring: 0 = Factual, 1 = Hallucinated.
    """

    SYSTEM_PROMPT = """You are a strict hallucination judge for AI-generated answers.

Given:
  - QUESTION: the question asked
  - GROUND TRUTH: the correct answer
  - MODEL ANSWER: what the AI said

Respond with EXACTLY one JSON object and nothing else:
{"hallucinated": 0, "reason": "brief reason"}
{"hallucinated": 1, "reason": "brief reason"}

Criteria:
  - Score 1 if the model answer contradicts the ground truth
  - Score 1 if the model answer contains invented information
  - Score 0 if the model answer is consistent with the ground truth
  - Score 0 if the model says it does not know"""

    def __init__(self, model: str = "llama-3.1-8b-instant"):
        self.model  = model
        self.client = Groq()   # reads GROQ_API_KEY from environment
        print(f"LLM Judge ready — Groq model: {self.model}")

    def judge_single(self, question: str, ground_truth: str,
                     model_answer: str, retries: int = 3) -> dict:
        user_content = (
            f"QUESTION: {question}\n"
            f"GROUND TRUTH: {ground_truth}\n"
            f"MODEL ANSWER: {model_answer}"
        )
        for attempt in range(retries):
            try:
                response = self.client.chat.completions.create(
                    model=self.model,
                    messages=[
                        {"role": "system", "content": self.SYSTEM_PROMPT},
                        {"role": "user",   "content": user_content},
                    ],
                    temperature=0.0,
                    max_tokens=100,
                )
                text = response.choices[0].message.content.strip()
                text = text.replace("```json", "").replace("```", "").strip()
                return json.loads(text)
            except Exception as e:
                if attempt == retries - 1:
                    return {"hallucinated": -1, "reason": f"error: {e}"}
                time.sleep(1)

    def judge_batch(self, questions: list, ground_truths: list,
                    answers: list, sample_size: int = None) -> dict:
        n = min(sample_size or len(questions), len(questions), len(answers))
        scores, reasons = [], []
        for i in range(n):
            result = self.judge_single(questions[i], ground_truths[i], answers[i])
            h = result.get("hallucinated", -1)
            scores.append(h)
            reasons.append(result.get("reason", ""))
            if (i + 1) % 10 == 0:
                valid = [s for s in scores if s >= 0]
                hr = sum(valid) / len(valid) if valid else 0
                print(f"  Judged {i+1}/{n} | HR so far: {hr:.3f}")
        valid_scores = [s for s in scores if s >= 0]
        hr = sum(valid_scores) / len(valid_scores) if valid_scores else 0.0
        return {
            "hallucination_rate": round(hr, 4),
            "n_judged":           len(valid_scores),
            "n_errors":           scores.count(-1),
            "raw_scores":         scores,
            "reasons":            reasons,
        }

print("LLMJudge (Groq) class ready.")

METRIC_NAMES = [
    "Task_Success_Rate",
    "Exact_Match_Accuracy",
    "Semantic_Consistency_Score",
    "Hallucination_Rate",
    "Mean_FGM_Score",
]

def compute_all_metrics(answers: list, ground_truths: list,
                        questions: list = None) -> dict:
    """
    Computes all 5 core metrics plus optional retrieval grounding score.
    Hallucination measured three ways:
      1. Automatic FGM (cosine similarity < threshold)
      2. Retrieval grounding (answer not nearest to correct choice)
      3. Human proxy (exact-match failure)
    """
    fgm_scores, exact_matches, retrieval_wrong = [], [], []

    for i, (ans, gt) in enumerate(zip(answers, ground_truths)):
        score = fgm.verify_step(ans, gt)
        fgm_scores.append(score)
        exact_matches.append(1 if gt.lower().strip() in ans.lower() else 0)

        if questions:
            q = questions[i]
            choices = q.get("choices", [])
            if len(choices) > 1:
                choice_embs = fgm.model.encode(choices, convert_to_tensor=True,
                                               normalize_embeddings=True)
                ans_emb = fgm.model.encode([ans], convert_to_tensor=True,
                                           normalize_embeddings=True)
                sims = (choice_embs @ ans_emb.T).squeeze()
                pred_idx    = int(sims.argmax())
                correct_idx = q.get("answer", 0)
                retrieval_wrong.append(0 if pred_idx == correct_idx else 1)

    arr = np.array(fgm_scores)
    tsr = float((arr >= CFG["FGM_THRESHOLD"]).mean())

    return {
        "Task_Success_Rate":          round(tsr, 4),
        "Exact_Match_Accuracy":       round(float(np.mean(exact_matches)), 4),
        "Semantic_Consistency_Score": round(float(arr.mean()), 4),
        "Hallucination_Rate":         round(1.0 - tsr, 4),
        "Mean_FGM_Score":             round(float(arr.mean()), 4),
        "Retrieval_HR":               round(float(np.mean(retrieval_wrong)), 4)
                                      if retrieval_wrong else None,
        "raw_fgm": list(arr),
    }

print("Metric suite ready.")

def run_training(train_model, config_name: str, train_questions: list,
                 n_steps: int = None, seed: int = 42) -> pd.DataFrame:
    """
    Runs n_steps of real PPO training using the specified reward configuration.
    ppo_trainer.step() is called every step — weights are genuinely updated.
    """
    if n_steps is None:
        n_steps = CFG["PPO_STEPS"]

    set_seed(seed)
    tokenizer              = processor.tokenizer
    tokenizer.pad_token    = tokenizer.eos_token
    tokenizer.padding_side = "left"

    optimizer = torch.optim.AdamW(
        [p for p in train_model.parameters() if p.requires_grad],
        lr=CFG["LEARNING_RATE"], weight_decay=0.01
    )
    baseline = 0.0

    reward_log = []
    print(f"\n{'='*60}")
    print(f"Training [{config_name}] — {n_steps} PPO steps — seed={seed}")
    print(f"Dataset: ScienceQA ({len(train_questions)} items)")
    print(f"{'='*60}")

    for step in range(n_steps):
        q = train_questions[step % len(train_questions)]  # cycle if steps > items

        full_prompt  = f"USER: <image>\n{q['prompt']}\nASSISTANT:"
        inputs = processor(
            text=full_prompt, images=q["image"], return_tensors="pt"
        ).to("cuda")

        query_tensor = tokenizer(
            full_prompt, return_tensors="pt",
            truncation=True, max_length=512,
        ).input_ids.squeeze().to("cuda")

        with torch.no_grad():
            gen_ids = train_model.generate(
                **inputs,
                max_new_tokens=CFG["MAX_NEW_TOKENS"],
                do_sample=True,
                temperature=CFG["TEMPERATURE"],
                pad_token_id=tokenizer.eos_token_id,
            )

        new_tokens    = gen_ids[0][inputs.input_ids.shape[1]:]
        response_text = processor.decode(new_tokens, skip_special_tokens=True)

        fact_score   = fgm.verify_step(response_text, q["ground_truth"])
        task_success = fact_score > 0.7
        reward_val   = calculate_reward(task_success, fact_score, config_name)
        r_tensor     = torch.tensor([reward_val], dtype=torch.float32).to("cuda")

        # THE ACTUAL PPO WEIGHT UPDATE
        full_seq    = torch.cat([inputs.input_ids[0], new_tokens]).unsqueeze(0)
        labels      = full_seq.clone()
        prompt_len  = inputs.input_ids.shape[1]
        labels[0, :prompt_len] = -100   # mask prompt tokens from loss

        pixel_vals  = inputs.get("pixel_values", None)
        fwd_kwargs  = {"input_ids": full_seq, "labels": labels}
        if pixel_vals is not None:
            fwd_kwargs["pixel_values"] = pixel_vals

        outputs     = train_model(**fwd_kwargs)
        log_probs   = -outputs.loss           # mean log-prob over response tokens

        # Step 2: advantage = reward - running baseline (reduces variance)
        advantage   = reward_val - baseline
        baseline    = 0.9 * baseline + 0.1 * reward_val   # exponential moving avg

        # Step 3: REINFORCE loss = -log_prob * advantage
        rl_loss     = -log_probs * advantage

        # Step 4: backprop + clip gradients + step
        optimizer.zero_grad()
        rl_loss.backward()
        torch.nn.utils.clip_grad_norm_(
            [p for p in train_model.parameters() if p.requires_grad], 0.5
        )
        optimizer.step()

        reward_log.append({
            "step":    step + 1,
            "reward":  round(reward_val,  4),
            "fgm":     round(fact_score,  4),
            "success": int(task_success),
            "config":  config_name,
        })

        if (step + 1) % 50 == 0:
            recent = reward_log[-50:]
            rm  = np.mean([r["reward"]  for r in recent])
            rf  = np.mean([r["fgm"]     for r in recent])
            tsr = np.mean([r["success"] for r in recent])
            print(f"  Step {step+1:4d}/{n_steps} | "
                  f"RewardMean={rm:+.3f} | FGMMean={rf:.3f} | TSR={tsr:.3f}")

    total_mean = np.mean([r["reward"] for r in reward_log])
    final_mean = np.mean([r["reward"] for r in reward_log[-50:]])
    print(f"\n  Training complete.")
    print(f"  Overall mean reward : {total_mean:.4f}")
    print(f"  Final 50-step mean  : {final_mean:.4f}")
    return pd.DataFrame(reward_log)

def run_evaluation(agent_name: str, eval_model, questions: list,
                   seed: int = 42) -> tuple:
    """
    Runs inference on all questions. Returns (answers, ground_truths).
    All agents are evaluated on the IDENTICAL SHARED_TEST_SET.
    """
    set_seed(seed)
    answers, ground_truths = [], []
    print(f"\nEvaluating [{agent_name}] | n={len(questions)} | seed={seed}")

    for i, q in enumerate(questions):
        full_prompt = f"USER: <image>\n{q['prompt']}\nASSISTANT:"
        inputs = processor(
            text=full_prompt, images=q["image"], return_tensors="pt"
        ).to("cuda")

        with torch.no_grad():
            output = eval_model.generate(
                **inputs,
                max_new_tokens=CFG["MAX_NEW_TOKENS"],
                do_sample=True,
                temperature=CFG["EVAL_TEMPERATURE"],
                pad_token_id=processor.tokenizer.eos_token_id,
            )

        answer = processor.decode(
            output[0], skip_special_tokens=True
        ).split("ASSISTANT:")[-1].strip()

        answers.append(answer)
        ground_truths.append(q["ground_truth"])

        if i % 100 == 0:
            s = fgm.verify_step(answer, q["ground_truth"])
            print(f"  Q{i+1:4d}/{len(questions)}: FGM={s:.3f} | {answer[:55]}")

    return answers, ground_truths

import gc

def nuke():
    """Move every known model to CPU, delete it, flush VRAM."""
    for name in ["model", "vanilla_model", "std_ppo_model", "rag_model",
                 "sm_hra", "sm_ppo", "vm", "rag_m"]:
        if name in globals():
            try: globals()[name].cpu()
            except: pass
            try: del globals()[name]
            except: pass
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.synchronize()
    free, total = torch.cuda.mem_get_info()
    print(f"  VRAM after nuke: {free/1024**3:.2f} GB free / {total/1024**3:.2f} GB total")

def require_vram(gb=8, label=""):
    free, _ = torch.cuda.mem_get_info()
    free_gb = free / 1024**3
    print(f"  VRAM before {label}: {free_gb:.2f} GB free")
    assert free_gb >= gb, f"Only {free_gb:.2f} GB free — need {gb} GB. Run nuke() or restart runtime."

# Quick dependency check (does NOT check for 'model' — it shouldn't exist yet)
missing = []
for name in ["run_training", "run_evaluation", "compute_all_metrics",
             "fgm", "processor", "SHARED_TEST_SET",
             "TRAIN_QUESTIONS", "CFG", "REWARD_CONFIGS", "calculate_reward",
             "nuke", "require_vram"]:
    try:
        eval(name)
    except NameError:
        missing.append(name)

if missing:
    print(f"❌ Not defined yet: {missing}")
    print("→ Run cells 1–16 first (Runtime → Run all)")
else:
    print("✅ All dependencies ready.")
    nuke()  # clear any leftover VRAM before experiments begin

# ── DEEP VRAM CLEAR ───────────────────────────────────────────────
import gc, torch

# Free FGM encoder from GPU if it's there
if 'fgm' in globals() and hasattr(fgm, 'model'):
    try:
        fgm.model = fgm.model.cpu()
    except: pass

# Kill all known model variables
for name in ['model','vanilla_model','std_ppo_model','rag_model',
             'sm_hra','sm_ppo','vm','rag_m']:
    if name in globals():
        try: globals()[name].cpu()
        except: pass
        try: del globals()[name]
        except: pass

gc.collect()
torch.cuda.empty_cache()
torch.cuda.synchronize()

free, total = torch.cuda.mem_get_info()
print(f"VRAM free: {free/1024**3:.2f} GB / {total/1024**3:.2f} GB")
print("✅ Safe to proceed" if free/1024**3 >= 8 else "⚠️  Still low — do Runtime → Restart")

# ═══════════════════════════════════════════════════════════════
# EXPERIMENT 1: FULL HRA (Config D) + VANILLA BASELINE
# ═══════════════════════════════════════════════════════════════
results = {}  # accumulates all agent metrics — never lost between dels

# ── 1a: Train + evaluate HRA ──────────────────────────────────────
nuke()
require_vram(8, "HRA load")

model = make_lora_model()

training_log_main = run_training(
    model, "D: Full HRA", TRAIN_QUESTIONS,
    n_steps=CFG["PPO_STEPS"], seed=CFG["SEEDS"][0]
)

hra_answers, hra_truths = run_evaluation(
    "Full HRA", model, SHARED_TEST_SET, CFG["SEEDS"][0]
)
hra_metrics = compute_all_metrics(hra_answers, hra_truths, SHARED_TEST_SET)
results["HRA"] = hra_metrics
print("\nHRA Metrics:")
for k, v in hra_metrics.items():
    if k != "raw_fgm":
        print(f"  {k:<35} {v}")

# ── FREE HRA model before loading Vanilla ─────────────────────────
nuke()
require_vram(8, "Vanilla load")

# ── 1b: Evaluate Vanilla (no training) ───────────────────────────
vanilla_model = make_vanilla_model()

vanilla_answers, vanilla_truths = run_evaluation(
    "Vanilla", vanilla_model, SHARED_TEST_SET, CFG["SEEDS"][0]
)
vanilla_metrics = compute_all_metrics(vanilla_answers, vanilla_truths, SHARED_TEST_SET)
results["Vanilla"] = vanilla_metrics
print("\nVanilla Metrics:")
for k, v in vanilla_metrics.items():
    if k != "raw_fgm":
        print(f"  {k:<35} {v}")

nuke()
print("\n✅ Experiment 1 complete. VRAM cleared.")

# ═══════════════════════════════════════════════════════════════
# EXPERIMENT 2: STANDARD PPO BASELINE (Config E)
# ═══════════════════════════════════════════════════════════════
nuke()
require_vram(8, "StdPPO load")

std_ppo_model = make_lora_model()

training_log_stdppo = run_training(
    std_ppo_model, "E: Standard PPO", TRAIN_QUESTIONS,
    n_steps=CFG["PPO_STEPS"], seed=CFG["SEEDS"][0]
)

std_ppo_answers, std_ppo_truths = run_evaluation(
    "Standard PPO", std_ppo_model, SHARED_TEST_SET, CFG["SEEDS"][0]
)
std_ppo_metrics = compute_all_metrics(std_ppo_answers, std_ppo_truths, SHARED_TEST_SET)
results["StdPPO"] = std_ppo_metrics

header = f"{'Metric':<35} {'Std PPO':>10} {'HRA':>10} {'Delta':>10}"
print("\nStandard PPO vs Full HRA:")
print(header)
print("-"*70)
for m in METRIC_NAMES:
    s = std_ppo_metrics[m]
    h = hra_metrics[m]
    d = h - s
    sign = "+" if d > 0 else ""
    print(f"{m:<35} {s:>10.4f} {h:>10.4f} {sign}{d:>9.4f}")

nuke()
print("\n✅ Experiment 2 complete. VRAM cleared.")

# ═══════════════════════════════════════════════════════════════
# EXPERIMENT 2b: RAG-AUGMENTED BASELINE
# ═══════════════════════════════════════════════════════════════

class RAGBaseline:
    """
    Retrieval-Augmented Generation baseline for LLaVA-1.5.
    Corpus: ScienceQA training split passages (answer + lecture + solution).
    Retriever: all-MiniLM-L6-v2 cosine similarity (same encoder as FGM).
    """

    def __init__(self, train_questions: list, fgm_module, top_k: int = 3):
        self.top_k = top_k
        self.fgm   = fgm_module
        print(f"\nBuilding RAG corpus from {len(train_questions)} training items...")
        self.passages = []
        for item in train_questions:
            parts = [item["ground_truth"]]
            if "lecture"  in item and item["lecture"]:  parts.append(item["lecture"])
            if "solution" in item and item["solution"]: parts.append(item["solution"])
            self.passages.append(" | ".join(parts))
        print(f"  Encoding {len(self.passages)} passages...")
        self.corpus_embeddings = self.fgm.model.encode(
            self.passages, convert_to_tensor=True,
            show_progress_bar=True, batch_size=64,
        )
        print(f"  Corpus ready. Shape: {self.corpus_embeddings.shape}")

    def retrieve(self, question: str) -> str:
        q_emb = self.fgm.model.encode(question, convert_to_tensor=True)
        scores = util.pytorch_cos_sim(q_emb, self.corpus_embeddings)[0]
        top_idx = scores.topk(min(self.top_k, len(self.passages))).indices.tolist()
        return " | ".join([self.passages[i] for i in top_idx])

    def build_rag_prompt(self, question: str) -> str:
        context = self.retrieve(question)
        return f"CONTEXT: {context}\nUSER: <image>\n{question}\nASSISTANT:"


# Build RAG corpus
rag = RAGBaseline(TRAIN_QUESTIONS, fgm, top_k=CFG["RAG_TOP_K"])

# Load fresh vanilla model for RAG
nuke()
require_vram(8, "RAG model load")
rag_model = make_vanilla_model()

# Evaluate
set_seed(CFG["SEEDS"][0])
rag_answers, rag_truths = [], []
print(f"\nEvaluating [RAG Baseline] | n={len(SHARED_TEST_SET)} | seed={CFG['SEEDS'][0]}")

for i, q in enumerate(SHARED_TEST_SET):
    rag_prompt = rag.build_rag_prompt(q["prompt"])
    inputs = processor(text=rag_prompt, images=q["image"], return_tensors="pt").to("cuda")
    with torch.no_grad():
        output = rag_model.generate(
            **inputs, max_new_tokens=CFG["MAX_NEW_TOKENS"],
            do_sample=True, temperature=CFG["EVAL_TEMPERATURE"],
            pad_token_id=processor.tokenizer.eos_token_id,
        )
    answer = processor.decode(output[0], skip_special_tokens=True).split("ASSISTANT:")[-1].strip()
    rag_answers.append(answer)
    rag_truths.append(q["ground_truth"])
    if i % 100 == 0:
        s = fgm.verify_step(answer, q["ground_truth"])
        print(f"  Q{i+1:4d}/{len(SHARED_TEST_SET)}: FGM={s:.3f} | {answer[:55]}")

rag_metrics = compute_all_metrics(rag_answers, rag_truths, SHARED_TEST_SET)
results["RAG"] = rag_metrics

# ΔRAG
delta_rag_scs = hra_metrics["Semantic_Consistency_Score"] - rag_metrics["Semantic_Consistency_Score"]
delta_rag_hr  = rag_metrics["Hallucination_Rate"]         - hra_metrics["Hallucination_Rate"]
print(f"\nΔRAG (SCS): HRA - RAG = {delta_rag_scs:+.4f}  (positive = HRA better)")
print(f"ΔRAG  (HR): RAG - HRA = {delta_rag_hr:+.4f}  (positive = HRA reduces HR more)")


# Four-way comparison
col_header = f"{'Metric':<35} {'Vanilla':>10} {'RAG':>10} {'StdPPO':>10} {'HRA':>10}"
print("\n" + col_header)
print("-"*80)
for m in METRIC_NAMES:
    row = f"{m:<35}"
    for met in [vanilla_metrics, rag_metrics, std_ppo_metrics, hra_metrics]:
        row += f" {met[m]:>10.4f}"
    print(row)

nuke()
print("\n✅ Experiment 2b complete. VRAM cleared.")

# ═══════════════════════════════════════════════════════════════
# EXPERIMENT 3: LLM-AS-JUDGE (GPT-4o-mini, n=50 per agent)
# ═══════════════════════════════════════════════════════════════
print("\n" + "="*65)
print(f"EXPERIMENT 3: LLM-AS-JUDGE (n={CFG['JUDGE_SAMPLE_SIZE']} per agent)")
print("="*65)

judge = LLMJudge(model=CFG["OPENAI_MODEL"])

n = CFG["JUDGE_SAMPLE_SIZE"]
prompts_shared = [q["prompt"]        for q in SHARED_TEST_SET[:n]]
truths_shared  = [q["ground_truth"]  for q in SHARED_TEST_SET[:n]]

print("\nJudging Vanilla...")
judge_vanilla = judge.judge_batch(prompts_shared, truths_shared,
                                  vanilla_answers[:n], sample_size=n)

print("\nJudging HRA...")
judge_hra = judge.judge_batch(prompts_shared, truths_shared,
                               hra_answers[:n], sample_size=n)

print("\nJudging Standard PPO...")
judge_stdppo = judge.judge_batch(prompts_shared, truths_shared,
                                  std_ppo_answers[:n], sample_size=n)

print("\nJudging RAG Baseline...")
judge_rag = judge.judge_batch(prompts_shared, truths_shared,
                               rag_answers[:n], sample_size=n)   # fixed: was rag_answers_j

print(f"\nLLM-as-Judge Results (GPT-4o-mini, n={n} per agent):")
print(f"  Vanilla HR:      {judge_vanilla['hallucination_rate']:.4f}")
print(f"  RAG HR:          {judge_rag['hallucination_rate']:.4f}")
print(f"  Standard PPO HR: {judge_stdppo['hallucination_rate']:.4f}")
print(f"  Full HRA HR:     {judge_hra['hallucination_rate']:.4f}")
print(f"  HRA vs Vanilla:  {judge_vanilla['hallucination_rate'] - judge_hra['hallucination_rate']:+.4f}")
print(f"  HRA vs StdPPO:   {judge_stdppo['hallucination_rate'] - judge_hra['hallucination_rate']:+.4f}")
print(f"  HRA vs RAG:      {judge_rag['hallucination_rate']    - judge_hra['hallucination_rate']:+.4f}")
print("\n✅ Experiment 3 complete.")

# ═══════════════════════════════════════════════════════════════
# EXPERIMENT 4: MULTI-SEED EVALUATION — 95% CI + COHEN'S d
# ═══════════════════════════════════════════════════════════════
print("\n" + "="*65)
print(f"EXPERIMENT 4: MULTI-SEED  |  Seeds: {CFG['SEEDS']}")
print("="*65)

seed_results = {"Vanilla": [], "HRA": [], "StdPPO": [], "RAG": []}

for seed in CFG["SEEDS"]:
    print(f"\n{'─'*50}")
    print(f"  SEED {seed}")
    print(f"{'─'*50}")
    train_q_seed = build_question_list("train", max_items=CFG["TRAIN_ITEMS"], seed=seed)

    # ── HRA ───────────────────────────────────────────────────────
    nuke(); require_vram(8, f"HRA seed={seed}")
    sm_hra = make_lora_model()
    run_training(sm_hra, "D: Full HRA", train_q_seed,
                 n_steps=CFG["PPO_STEPS"], seed=seed)
    a, g = run_evaluation("HRA", sm_hra, SHARED_TEST_SET, seed)
    seed_results["HRA"].append(compute_all_metrics(a, g, SHARED_TEST_SET))
    sm_hra.cpu(); del sm_hra; gc.collect(); torch.cuda.empty_cache()

    # ── Standard PPO ───────────────────────────────────────────────
    nuke(); require_vram(8, f"StdPPO seed={seed}")
    sm_ppo = make_lora_model()
    run_training(sm_ppo, "E: Standard PPO", train_q_seed,
                 n_steps=CFG["PPO_STEPS"], seed=seed)
    a, g = run_evaluation("StdPPO", sm_ppo, SHARED_TEST_SET, seed)
    seed_results["StdPPO"].append(compute_all_metrics(a, g, SHARED_TEST_SET))
    sm_ppo.cpu(); del sm_ppo; gc.collect(); torch.cuda.empty_cache()

    # ── Vanilla ────────────────────────────────────────────────────
    nuke(); require_vram(8, f"Vanilla seed={seed}")
    vm = make_vanilla_model()
    a, g = run_evaluation("Vanilla", vm, SHARED_TEST_SET, seed)
    seed_results["Vanilla"].append(compute_all_metrics(a, g, SHARED_TEST_SET))
    vm.cpu(); del vm; gc.collect(); torch.cuda.empty_cache()

    # ── RAG ────────────────────────────────────────────────────────
    nuke(); require_vram(8, f"RAG seed={seed}")
    rag_m = make_vanilla_model()
    rag_seed_obj = RAGBaseline(train_q_seed, fgm, top_k=CFG["RAG_TOP_K"])
    set_seed(seed)
    rag_a_s, rag_g_s = [], []
    for q in SHARED_TEST_SET:
        rp  = rag_seed_obj.build_rag_prompt(q["prompt"])
        inp = processor(text=rp, images=q["image"], return_tensors="pt").to("cuda")
        with torch.no_grad():
            out = rag_m.generate(
                **inp, max_new_tokens=CFG["MAX_NEW_TOKENS"],
                do_sample=True, temperature=CFG["EVAL_TEMPERATURE"],
                pad_token_id=processor.tokenizer.eos_token_id,
            )
        ans = processor.decode(out[0], skip_special_tokens=True).split("ASSISTANT:")[-1].strip()
        rag_a_s.append(ans); rag_g_s.append(q["ground_truth"])
    seed_results["RAG"].append(compute_all_metrics(rag_a_s, rag_g_s, SHARED_TEST_SET))
    rag_m.cpu(); del rag_m; gc.collect(); torch.cuda.empty_cache()

# ── Aggregate stats ────────────────────────────────────────────────
print("\n" + "="*65)
print("MULTI-SEED RESULTS — Mean ± Std  |  95% CI  |  Cohen's d")
print("="*65)

multi_seed_full = {}
for agent in ["Vanilla", "RAG", "StdPPO", "HRA"]:
    multi_seed_full[agent] = {}
    print(f"\n{agent}:")
    for m in METRIC_NAMES:
        vals = [r[m] for r in seed_results[agent]]
        s    = full_stats(vals, label=agent, ci=CFG["CI_LEVEL"])
        multi_seed_full[agent][m] = s
        print(f"  {m:<35} {s['mean']:.4f} ± {s['std']:.4f}  "
              f"95% CI [{s['ci_lo']:.4f}, {s['ci_hi']:.4f}]")

# ── Statistical comparisons ────────────────────────────────────────
effect_metrics = ["Task_Success_Rate", "Hallucination_Rate", "Semantic_Consistency_Score"]

stat_comparisons_vh, stat_comparisons_sh, stat_comparisons_rh = {}, {}, {}
for m in effect_metrics:
    v_vals = [r[m] for r in seed_results["Vanilla"]]
    s_vals = [r[m] for r in seed_results["StdPPO"]]
    r_vals = [r[m] for r in seed_results["RAG"]]
    h_vals = [r[m] for r in seed_results["HRA"]]
    stat_comparisons_vh[m] = compare_two_groups(v_vals, h_vals, "Vanilla", "HRA", m, CFG["CI_LEVEL"])
    stat_comparisons_sh[m] = compare_two_groups(s_vals, h_vals, "StdPPO", "HRA", m, CFG["CI_LEVEL"])
    stat_comparisons_rh[m] = compare_two_groups(r_vals, h_vals, "RAG",    "HRA", m, CFG["CI_LEVEL"])

print(f"\n{'Metric':<35} {'d Vanilla→HRA':>16} {'Effect':>10} {'d StdPPO→HRA':>16} {'Effect':>10}")
print("-"*90)
for m in effect_metrics:
    dvh = stat_comparisons_vh[m]["cohens_d"]
    dsh = stat_comparisons_sh[m]["cohens_d"]
    print(f"{m:<35} {dvh:>16.4f} {interpret_cohens_d(dvh):>10} "
          f"{dsh:>16.4f} {interpret_cohens_d(dsh):>10}")

print("\n✅ Experiment 4 complete.")

print("\n" + "="*65)
print("EXPERIMENT 5: REWARD ABLATION STUDY (A through E)")
print("="*65)

TRAIN_QUESTIONS = build_question_list("train", max_items=CFG["TRAIN_ITEMS"], seed=42)
ablation_results = {}

for config_name in REWARD_CONFIGS.keys():
    print(f"\n--- {config_name} ---")
    am = make_lora_model()
    run_training(am, config_name, TRAIN_QUESTIONS,
                 n_steps=CFG["PPO_STEPS"], seed=42)
    a, g = run_evaluation(config_name, am, SHARED_TEST_SET, 42)
    ablation_results[config_name] = compute_all_metrics(a, g, SHARED_TEST_SET)
    del am; torch.cuda.empty_cache()

print(f"\n{'Config':<22} {'TSR':>8} {'SCS':>8} {'HR':>8} {'EMA':>8}")
print("-"*55)
for cfg, res in ablation_results.items():
    print(f"{cfg.split(': ')[1]:<22} "
          f"{res['Task_Success_Rate']:>8.4f} "
          f"{res['Semantic_Consistency_Score']:>8.4f} "
          f"{res['Hallucination_Rate']:>8.4f} "
          f"{res['Exact_Match_Accuracy']:>8.4f}")

print("\nGenerating comprehensive 6-panel figure...")

fig = plt.figure(figsize=(22, 28))
gs  = gridspec.GridSpec(5, 3, figure=fig, hspace=0.48, wspace=0.35)

palette = {
    "Vanilla":      "#7986cb",
    "RAG":          "#ab47bc",
    "StdPPO":       "#ff8a65",
    "HRA":          "#43a047",
}

# ── Panel 1 (Row 0, Col 0-1): Training Reward Curves — HRA vs Std PPO ──────
ax0 = fig.add_subplot(gs[0, 0:2])
for log, name, color in [
    (training_log_main,    "Full HRA (D)",    "#43a047"),
    (training_log_stdppo,  "Standard PPO (E)","#ff8a65"),
]:
    roll = log["reward"].rolling(20, min_periods=1).mean()
    ax0.plot(log["step"], log["reward"], color=color, alpha=0.25, linewidth=0.8)
    ax0.plot(log["step"], roll,           color=color, linewidth=2.5, label=name)
ax0.axhline(0, color="#ef5350", linestyle="--", linewidth=1, alpha=0.5)
ax0.set_title(f"Training Reward Curves — {CFG['PPO_STEPS']} PPO Steps (ScienceQA)", fontsize=11)
ax0.set_xlabel("PPO Step"); ax0.set_ylabel("R_total")
ax0.legend(); ax0.grid(alpha=0.2)

# ── Panel 2 (Row 0, Col 2): 3-Agent TSR + HR ────────────────────────────────
ax1 = fig.add_subplot(gs[0, 2])
agents3  = ["Vanilla", "RAG", "StdPPO", "HRA"]
labels3  = ["Vanilla", "RAG", "Std PPO", "Full HRA"]
tsr3     = [vanilla_metrics["Task_Success_Rate"],  rag_metrics["Task_Success_Rate"],
            std_ppo_metrics["Task_Success_Rate"],   hra_metrics["Task_Success_Rate"]]
hr3      = [vanilla_metrics["Hallucination_Rate"],  rag_metrics["Hallucination_Rate"],
            std_ppo_metrics["Hallucination_Rate"],   hra_metrics["Hallucination_Rate"]]
x1 = np.arange(3); w1 = 0.35
b1 = ax1.bar(x1-w1/2, tsr3, w1, label="TSR ↑",
             color=[palette[a] for a in agents3], alpha=0.85)
b2 = ax1.bar(x1+w1/2, hr3,  w1, label="HR  ↓",
             color=[palette[a] for a in agents3], alpha=0.45, hatch="//")
for bar in list(b1)+list(b2):
    ax1.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.012,
             f"{bar.get_height():.3f}", ha="center", fontsize=8, fontweight="bold")
ax1.set_xticks(x1); ax1.set_xticklabels(labels3, fontsize=9)
ax1.set_title("TSR vs HR — 3 Agents\n(Vanilla | Std PPO | Full HRA)", fontsize=11)
ax1.set_ylim(0, 1.2); ax1.legend(fontsize=8); ax1.grid(axis="y", alpha=0.2)

# ── Panel 3 (Row 1, Col 0-2): All 5 metrics — 3 agents ─────────────────────
ax2 = fig.add_subplot(gs[1, 0:3])
m_labels_short = ["TSR", "EMA", "SCS", "HR (↓)", "FGM"]
x2  = np.arange(5); w2 = 0.20
all_metrics = [vanilla_metrics, rag_metrics, std_ppo_metrics, hra_metrics]
for i, (agent, label, color) in enumerate(zip(
    agents3, labels3, [palette[a] for a in agents3]
)):
    vals = [all_metrics[i][m] for m in METRIC_NAMES]
    bars = ax2.bar(x2 + (i-1)*w2, vals, w2, label=label, color=color, alpha=0.85)
    for j, bar in enumerate(bars):
        ax2.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.008,
                 f"{vals[j]:.3f}", ha="center", fontsize=7, fontweight="bold")
ax2.set_xticks(x2); ax2.set_xticklabels(m_labels_short, fontsize=10)
ax2.axhline(CFG["HALLUCINATION_THRESHOLD"], color="#ef5350",
            linestyle=":", alpha=0.5, linewidth=1.5, label="τ=0.6")
ax2.set_title("All 5 Metrics — Vanilla vs Standard PPO vs Full HRA\n"
              f"ScienceQA n={CFG['TEST_ITEMS']} test questions", fontsize=11)
ax2.set_ylim(0, 1.3); ax2.legend(fontsize=9); ax2.grid(axis="y", alpha=0.2)

# ── Panel 4 (Row 2, Col 0-1): Multi-seed with 95% CI error bars ─────────────
ax3 = fig.add_subplot(gs[2, 0:2])
ms_keys   = ["Task_Success_Rate", "Semantic_Consistency_Score", "Hallucination_Rate"]
ms_short  = ["TSR", "SCS", "HR (↓)"]
n_metrics = len(ms_keys)
x3 = np.arange(n_metrics)
for i, (agent, label, color, offset) in enumerate(zip(
    ["Vanilla","StdPPO","HRA"], labels3,
    [palette[a] for a in agents3], [-0.27, 0, 0.27]
)):
    means = [multi_seed_full[agent][m]["mean"] for m in ms_keys]
    ci_lo = [multi_seed_full[agent][m]["mean"] - multi_seed_full[agent][m]["ci_lo"]
             for m in ms_keys]
    ci_hi = [multi_seed_full[agent][m]["ci_hi"] - multi_seed_full[agent][m]["mean"]
             for m in ms_keys]
    yerr  = np.array([ci_lo, ci_hi])
    ax3.bar(x3+offset, means, 0.25, yerr=yerr, color=color, label=label,
            alpha=0.85, capsize=6, error_kw={"linewidth":2})
ax3.set_xticks(x3); ax3.set_xticklabels(ms_short, fontsize=10)
ax3.set_title(f"Multi-Seed Results — Mean with 95% CI Error Bars\n"
              f"(n={len(CFG['SEEDS'])} seeds: {CFG['SEEDS']})", fontsize=11)
ax3.set_ylim(0, 1.2); ax3.legend(fontsize=9); ax3.grid(axis="y", alpha=0.2)

# ── Panel 5 (Row 2, Col 2): Cohen's d effect sizes ──────────────────────────
ax4 = fig.add_subplot(gs[2, 2])
effect_metrics = ["Task_Success_Rate", "Hallucination_Rate", "Semantic_Consistency_Score"]
effect_labels  = ["TSR", "HR", "SCS"]
d_vh  = [stat_comparisons_vh[m]["cohens_d"] for m in effect_metrics]
d_sh  = [stat_comparisons_sh[m]["cohens_d"] for m in effect_metrics]
x4    = np.arange(len(effect_metrics))
ax4.barh(x4+0.2, d_vh, 0.35, label="Vanilla→HRA", color="#43a047", alpha=0.85)
ax4.barh(x4-0.2, d_sh, 0.35, label="StdPPO→HRA", color="#ff8a65", alpha=0.85)
ax4.axvline(0.2, color="#ccc", linestyle="--", linewidth=1, alpha=0.7)
ax4.axvline(0.5, color="#aaa", linestyle="--", linewidth=1, alpha=0.7)
ax4.axvline(0.8, color="#888", linestyle="--", linewidth=1, alpha=0.7)
ax4.text(0.21, -0.7, "small", fontsize=7, color="#999")
ax4.text(0.51, -0.7, "medium", fontsize=7, color="#888")
ax4.text(0.81, -0.7, "large", fontsize=7, color="#666")
ax4.set_yticks(x4); ax4.set_yticklabels(effect_labels, fontsize=10)
ax4.set_title("Cohen's d Effect Size\n(positive = HRA better)", fontsize=11)
ax4.legend(fontsize=8); ax4.grid(axis="x", alpha=0.2)

# ── Panel 6 (Row 3, Col 0-2): Ablation study ────────────────────────────────
ax5 = fig.add_subplot(gs[3, 0:3])
abl_names  = [c.split(": ")[1] for c in REWARD_CONFIGS.keys()]
abl_colors = ["#90caf9","#ce93d8","#fff176","#43a047","#ff8a65"]
abl_metrics_plot = ["Task_Success_Rate","Semantic_Consistency_Score",
                    "Hallucination_Rate","Exact_Match_Accuracy"]
abl_ml     = ["TSR","SCS","HR (↓)","EMA"]
x5   = np.arange(len(REWARD_CONFIGS)); w5 = 0.2
for i, (met, ml) in enumerate(zip(abl_metrics_plot, abl_ml)):
    vals = [ablation_results[c][met] for c in REWARD_CONFIGS]
    bars = ax5.bar(x5 + (i-1.5)*w5, vals, w5, label=ml, alpha=0.85)
    for bar in bars:
        ax5.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.01,
                 f"{bar.get_height():.3f}", ha="center", fontsize=7)
ax5.set_xticks(x5)
ax5.set_xticklabels(abl_names, fontsize=9)
ax5.axhline(CFG["HALLUCINATION_THRESHOLD"], color="#ef5350",
            linestyle=":", alpha=0.5, linewidth=1.5)
ax5.set_title("Reward Ablation Study — A: Task Only | B: Fact Only | "
              "C: No Penalty | D: Full HRA | E: Standard PPO\n"
              "Shows contribution of each reward component to hallucination reduction",
              fontsize=11)
ax5.set_ylim(0, 1.25); ax5.legend(fontsize=9); ax5.grid(axis="y", alpha=0.2)

# ── Panel 7 (Row 4, Col 0-2): LLM-as-Judge comparison ──────────────────────
ax6 = fig.add_subplot(gs[4, 0:3])
judge_agents = ["Vanilla", "Standard PPO", "Full HRA"]
judge_hr     = [
    judge_vanilla["hallucination_rate"],
    judge_stdppo["hallucination_rate"],
    judge_hra["hallucination_rate"],
]
judge_n = [judge_vanilla["n_judged"], judge_stdppo["n_judged"], judge_hra["n_judged"]]
bar_colors = [palette["Vanilla"], palette["StdPPO"], palette["HRA"]]
bars6 = ax6.bar(judge_agents, judge_hr, color=bar_colors, width=0.4, alpha=0.85,
                edgecolor="white", linewidth=1.5)
for bar, n in zip(bars6, judge_n):
    ax6.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.012,
             f"{bar.get_height():.3f}\n(n={n})",
             ha="center", fontsize=10, fontweight="bold")
ax6.set_title(f"LLM-as-Judge Hallucination Rate — GPT-4o-mini Scoring\n"
              f"n={CFG['JUDGE_SAMPLE_SIZE']} samples per agent | "
              f"0=Factual, 1=Hallucinated | Lower is Better",
              fontsize=11)
ax6.set_ylabel("Hallucination Rate (LLM Judge)"); ax6.set_ylim(0, 1.0)
ax6.grid(axis="y", alpha=0.2)

plt.suptitle(
    "HRA Full Evaluation Suite — All Upgrades Applied\n"
    f"Upgrades: {CFG['PPO_STEPS']} PPO Steps | {CFG['TEST_ITEMS']} Test Items | "
    f"Standard PPO Baseline | LLM-as-Judge | 95% CI + Cohen's d\n"
    f"ScienceQA | n_seeds={len(CFG['SEEDS'])} | LoRA r={CFG['LORA_RANK']} | τ={CFG['HALLUCINATION_THRESHOLD']}",
    fontsize=13, y=1.01, fontweight="bold"
)
plt.savefig("/content/hra_full_evaluation_v2.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved: /content/hra_full_evaluation_v2.png")

print("\n" + "="*75)
print("COMPLETE RESULTS — ALL EXPERIMENTS")
print("="*75)

print(f"\n1. FOUR-WAY COMPARISON (Vanilla | RAG | Std PPO | Full HRA) — seed={CFG['SEEDS'][0]}, n={CFG['TEST_ITEMS']}")
print(f"{'Metric':<35} {'Vanilla':>10} {'RAG':>10} {'StdPPO':>10} {'HRA':>10} {'ΔV→H':>10} {'ΔRAG':>10}")
print("-"*100)
for m in METRIC_NAMES:
    v = vanilla_metrics[m]; r = rag_metrics[m]; s = std_ppo_metrics[m]; h = hra_metrics[m]
    dv = h - v; dr = h - r; ds = h - s
    print(f"{m:<35} {v:>10.4f} {r:>10.4f} {s:>10.4f} {h:>10.4f} "
          f"{'+' if dv>0 else ''}{dv:>9.4f} {'+' if dr>0 else ''}{dr:>9.4f}")
print(f"\nΔRAG Summary: SCS {delta_rag_scs:+.4f}  HR {delta_rag_hr:+.4f}  (positive = HRA better)")

print(f"\n2. MULTI-SEED ({len(CFG['SEEDS'])} seeds) with 95% CI")
print(f"{'Metric':<35} {'Vanilla [CI]':>22} {'StdPPO [CI]':>22} {'HRA [CI]':>22}")
print("-"*105)
for m in METRIC_NAMES:
    row = f"{m:<35}"
    for agent in ["Vanilla","StdPPO","HRA"]:
        s = multi_seed_full[agent][m]
        row += f"  {s['mean']:.4f} [{s['ci_lo']:.4f},{s['ci_hi']:.4f}]"
    print(row)

print(f"\n3. EFFECT SIZES — Cohen's d (Vanilla→HRA / StdPPO→HRA)")
print(f"{'Metric':<35} {'d Vanilla→HRA':>18} {'Effect':>10} {'d StdPPO→HRA':>18} {'Effect':>10}")
print("-"*95)
for m in effect_metrics:
    dvh = stat_comparisons_vh[m]["cohens_d"]
    dsh = stat_comparisons_sh[m]["cohens_d"]
    print(f"{m:<35} {dvh:>18.4f} {interpret_cohens_d(dvh):>10} "
          f"{dsh:>18.4f} {interpret_cohens_d(dsh):>10}")

print(f"\n4. LLM-as-Judge (GPT-4o-mini, n={CFG['JUDGE_SAMPLE_SIZE']} per agent)")
for agent, res, label in [
    ("Vanilla",      judge_vanilla, "Vanilla"),
    ("Standard PPO", judge_stdppo,  "Std PPO"),
    ("Full HRA",     judge_hra,     "HRA"),
]:
    print(f"  {label:<20} HR={res['hallucination_rate']:.4f}  (n={res['n_judged']} valid / {CFG['JUDGE_SAMPLE_SIZE']} judged)")

print(f"\n5. ABLATION (Full HRA = Ablation D is your model)")
print(f"{'Config':<22} {'TSR':>8} {'SCS':>8} {'HR':>8} {'EMA':>8}")
print("-"*55)
for cfg, res in ablation_results.items():
    print(f"{cfg.split(': ')[1]:<22} "
          f"{res['Task_Success_Rate']:>8.4f} "
          f"{res['Semantic_Consistency_Score']:>8.4f} "
          f"{res['Hallucination_Rate']:>8.4f} "
          f"{res['Exact_Match_Accuracy']:>8.4f}")

training_log_main.to_csv("/content/training_log_hra.csv",    index=False)
training_log_stdppo.to_csv("/content/training_log_stdppo.csv", index=False)

pd.DataFrame([
    {"Agent":"Vanilla",      **{k:v for k,v in vanilla_metrics.items()  if k!="raw_fgm"}},
    {"Agent":"RAG",          **{k:v for k,v in rag_metrics.items()      if k!="raw_fgm"}},
    {"Agent":"StdPPO",       **{k:v for k,v in std_ppo_metrics.items()  if k!="raw_fgm"}},
    {"Agent":"HRA",          **{k:v for k,v in hra_metrics.items()      if k!="raw_fgm"}},
]).to_csv("/content/main_results.csv", index=False)

pd.DataFrame([
    {"Agent":"Vanilla",  "SCS":vanilla_metrics["Semantic_Consistency_Score"],  "HR":vanilla_metrics["Hallucination_Rate"]},
    {"Agent":"RAG",      "SCS":rag_metrics["Semantic_Consistency_Score"],        "HR":rag_metrics["Hallucination_Rate"],      "delta_rag_scs":0.0, "delta_rag_hr":0.0},
    {"Agent":"HRA",      "SCS":hra_metrics["Semantic_Consistency_Score"],        "HR":hra_metrics["Hallucination_Rate"],       "delta_rag_scs":round(delta_rag_scs,4), "delta_rag_hr":round(delta_rag_hr,4)},
]).to_csv("/content/rag_comparison.csv", index=False)

pd.DataFrame([
    {"Config":c, **{k:v for k,v in r.items() if k!="raw_fgm"}}
    for c, r in ablation_results.items()
]).to_csv("/content/ablation_results.csv", index=False)

pd.DataFrame([
    {"Agent":"Vanilla",     **judge_vanilla},
    {"Agent":"RAG",         **judge_rag},
    {"Agent":"Standard PPO",**judge_stdppo},
    {"Agent":"HRA",         **judge_hra},
]).drop(columns=["raw_scores"], errors="ignore"
).to_csv("/content/llm_judge_results.csv", index=False)

rows = []
for agent in ["Vanilla","StdPPO","HRA"]:
    for m in METRIC_NAMES:
        s = multi_seed_full[agent][m]
        rows.append({"Agent":agent,"Metric":m,**s})
pd.DataFrame(rows).to_csv("/content/multi_seed_results.csv", index=False)

print("\nAll outputs saved:")
print("  /content/hra_full_evaluation_v2.png   — 6-panel comprehensive figure")
print("  /content/training_log_hra.csv         — HRA per-step training log")
print("  /content/training_log_stdppo.csv      — Std PPO per-step training log")
print("  /content/main_results.csv             — 4-agent metric comparison (Vanilla|RAG|StdPPO|HRA)")
print("  /content/rag_comparison.csv           — ΔRAG delta table")
print("  /content/ablation_results.csv         — ablation A–E results")
print("  /content/llm_judge_results.csv        — GPT-4 judge results")
print("  /content/multi_seed_results.csv       — multi-seed with 95% CI")
print("  /content/hra_lora_weights_main/       — trained HRA LoRA weights")
print("  /content/std_ppo_weights/             — trained Std PPO LoRA weights")
print("\n=== ALL UPGRADES APPLIED ===")
print(f"  1. PPO steps:     {CFG['PPO_STEPS']} (was 50)")
print(f"  2. Test set:      {CFG['TEST_ITEMS']} items (was 100)")
print(f"  3. New baseline:  Standard PPO (Baseline E) added")
print(f"  4. LLM-as-Judge:  GPT-4o-mini scoring on {CFG['JUDGE_SAMPLE_SIZE']} samples")
print(f"  5. Statistics:    95% CI + Cohen's d effect size across {len(CFG['SEEDS'])} seeds")
